// Package mcpserver exposes the assistant's custom tools to the headless Claude over loopback
// HTTP. Tools are split across two named MCP servers — "memory" (recall/propose) and "reminders"
// (schedule/list/cancel) — so each chat can enable and gate them independently. Every call
// carries chat_id (and user_id), and the server routes to that chat's isolated scheduler/memory.
// A per-chat mcp.json (generated by the chat package) tells claude which of these — plus any
// registered external servers — to connect.
package mcpserver

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	"assistant/internal/config"
	"assistant/internal/schedule"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// ChatScheduler routes scheduling to a chat's isolated scheduler.
type ChatScheduler interface {
	Scheduler(chatID int64) (*schedule.Scheduler, bool)
}

// ProposalSink backs propose_memory (asks the user to confirm, commits on approval).
type ProposalSink interface {
	Propose(ctx context.Context, chatID, userID int64, scope, content string) (string, error)
}

// MemoryRecaller backs recall_memory: the daemon searches a chat's memory and returns snippets.
type MemoryRecaller interface {
	Recall(chatID int64, query, date string, limit int) (string, error)
}

// ToolGate decides whether a user may use a named MCP server in a chat. It encodes the chat's
// per-chat allow-lists (all-users vs cron-admins). It's the server-side backstop to the
// client-side --allowedTools pre-approval.
type ToolGate interface {
	ToolAllowed(chatID, userID int64, server string) bool
}

// Server wraps two MCP servers (memory + reminders) and serves them over HTTP.
type Server struct {
	mem    *server.MCPServer
	rem    *server.MCPServer
	sch    ChatScheduler
	sink   ProposalSink
	recall MemoryRecaller
	gate   ToolGate
}

// New builds the MCP servers and registers the chat-aware tools.
func New(sch ChatScheduler, sink ProposalSink, recall MemoryRecaller, gate ToolGate) *Server {
	s := &Server{
		mem:    server.NewMCPServer("memory", "0.2.0"),
		rem:    server.NewMCPServer("reminders", "0.2.0"),
		sch:    sch,
		sink:   sink,
		recall: recall,
		gate:   gate,
	}
	s.registerTools()
	return s
}

// Serve runs both MCP endpoints (memory + reminders) on one HTTP listener until ctx is cancelled.
func (s *Server) Serve(ctx context.Context, addr string) error {
	mux := http.NewServeMux()
	memPath := config.BuiltinMCPServers[config.ServerMemory]
	remPath := config.BuiltinMCPServers[config.ServerReminders]
	mux.Handle(memPath, server.NewStreamableHTTPServer(s.mem, server.WithEndpointPath(memPath)))
	mux.Handle(remPath, server.NewStreamableHTTPServer(s.rem, server.WithEndpointPath(remPath)))
	httpSrv := &http.Server{Addr: addr, Handler: mux}

	errc := make(chan error, 1)
	go func() {
		log.Printf("mcp: serving on http://%s%s and %s", addr, memPath, remPath)
		errc <- httpSrv.ListenAndServe()
	}()
	select {
	case <-ctx.Done():
		shutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		return httpSrv.Shutdown(shutCtx)
	case err := <-errc:
		if err == http.ErrServerClosed {
			return nil
		}
		return err
	}
}

func (s *Server) registerTools() {
	// --- reminders server ---
	s.rem.AddTool(mcp.NewTool("schedule_reminder",
		mcp.WithDescription("Schedule a reminder or recurring job in THIS chat. Provide exactly one "+
			"timing: 'cron' (5-field) for recurring, OR 'delay_minutes' for a one-off N minutes from now, "+
			"OR 'at' (RFC3339) for a specific time."),
		mcp.WithNumber("chat_id", mcp.Required(), mcp.Description("Your current chat id.")),
		mcp.WithNumber("user_id", mcp.Required(), mcp.Description("The requesting user's id (for the access check).")),
		mcp.WithString("prompt", mcp.Required(), mcp.Description("What the assistant should do/say when it fires.")),
		mcp.WithString("cron", mcp.Description("5-field cron expression for a recurring job.")),
		mcp.WithNumber("delay_minutes", mcp.Description("Minutes from now for a one-off reminder.")),
		mcp.WithString("at", mcp.Description("RFC3339 timestamp for a one-off reminder.")),
	), s.handleSchedule)

	s.rem.AddTool(mcp.NewTool("list_reminders",
		mcp.WithDescription("List this chat's scheduled reminders/jobs."),
		mcp.WithNumber("chat_id", mcp.Required(), mcp.Description("Your current chat id.")),
		mcp.WithNumber("user_id", mcp.Required(), mcp.Description("The requesting user's id (for the access check).")),
	), s.handleList)

	s.rem.AddTool(mcp.NewTool("cancel_reminder",
		mcp.WithDescription("Cancel one of this chat's reminders by id."),
		mcp.WithNumber("chat_id", mcp.Required(), mcp.Description("Your current chat id.")),
		mcp.WithNumber("user_id", mcp.Required(), mcp.Description("The requesting user's id (for the access check).")),
		mcp.WithString("id", mcp.Required(), mcp.Description("The schedule id to cancel.")),
	), s.handleCancel)

	// --- memory server ---
	if s.recall != nil {
		s.mem.AddTool(mcp.NewTool("recall_memory",
			mcp.WithDescription("Search THIS chat's stored memory (older daily notes, long-term memory, and "+
				"user profiles) that isn't already in your context. Use it when the daily index mentions a day "+
				"or topic whose details you need. It is a keyword search, so include synonyms and alternate "+
				"phrasings in the query (e.g. 'trip vacation holiday travel'); if nothing comes back, rephrase "+
				"and try again. To open a specific day from the index, pass its date instead."),
			mcp.WithNumber("chat_id", mcp.Required(), mcp.Description("Your current chat id.")),
			mcp.WithNumber("user_id", mcp.Description("The requesting user's id (for the access check).")),
			mcp.WithString("query", mcp.Description("Keywords to search for; include synonyms. Omit if using 'date'.")),
			mcp.WithString("date", mcp.Description("A specific day to open, DD-MM-YY (e.g. 04-06-26). Omit if using 'query'.")),
			mcp.WithNumber("limit", mcp.Description("Max snippets to return (default 6).")),
		), s.handleRecall)
	}

	if s.sink != nil {
		s.mem.AddTool(mcp.NewTool("propose_memory",
			mcp.WithDescription("Propose saving a fact to THIS chat's memory. Does NOT save immediately: "+
				"the user is asked to confirm via Telegram and it's stored only on approval."),
			mcp.WithNumber("chat_id", mcp.Required(), mcp.Description("Your current chat id.")),
			mcp.WithString("content", mcp.Required(), mcp.Description("The fact to remember, phrased clearly.")),
			mcp.WithString("scope", mcp.Description("'long_term' (default) or 'user' for a fact about the current user.")),
			mcp.WithNumber("user_id", mcp.Description("The user id, required when scope is 'user'.")),
		), s.handlePropose)
	}
}

func (s *Server) handleSchedule(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	chatID, err := req.RequireInt("chat_id")
	if err != nil {
		return mcp.NewToolResultError("chat_id is required"), nil
	}
	userID := int64(req.GetInt("user_id", 0))
	if !s.gate.ToolAllowed(int64(chatID), userID, config.ServerReminders) {
		return mcp.NewToolResultError("You are not allowed to manage reminders in this chat."), nil
	}
	sched, ok := s.sch.Scheduler(int64(chatID))
	if !ok {
		return mcp.NewToolResultError("this chat is not active"), nil
	}
	prompt, err := req.RequireString("prompt")
	if err != nil {
		return mcp.NewToolResultError("prompt is required"), nil
	}

	sc := schedule.Schedule{ChatID: int64(chatID), Prompt: prompt}
	switch cronExpr, atStr, delay := req.GetString("cron", ""), req.GetString("at", ""), req.GetFloat("delay_minutes", 0); {
	case cronExpr != "":
		sc.Kind, sc.Spec = schedule.KindCron, cronExpr
	case atStr != "":
		t, perr := time.Parse(time.RFC3339, atStr)
		if perr != nil {
			return mcp.NewToolResultError("could not parse 'at' as RFC3339: " + perr.Error()), nil
		}
		sc.Kind, sc.FireAt = schedule.KindOnce, t
	case delay > 0:
		sc.Kind, sc.FireAt = schedule.KindOnce, time.Now().Add(time.Duration(delay*float64(time.Minute)))
	default:
		return mcp.NewToolResultError("provide one of: cron, delay_minutes, or at"), nil
	}

	saved, err := sched.Add(sc)
	if err != nil {
		return mcp.NewToolResultError("failed to schedule: " + err.Error()), nil
	}
	return mcp.NewToolResultText(fmt.Sprintf("Scheduled %s (id %s).", describe(saved), saved.ID)), nil
}

func (s *Server) handleList(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	chatID, err := req.RequireInt("chat_id")
	if err != nil {
		return mcp.NewToolResultError("chat_id is required"), nil
	}
	userID := int64(req.GetInt("user_id", 0))
	if !s.gate.ToolAllowed(int64(chatID), userID, config.ServerReminders) {
		return mcp.NewToolResultError("You are not allowed to view reminders in this chat."), nil
	}
	sched, ok := s.sch.Scheduler(int64(chatID))
	if !ok {
		return mcp.NewToolResultText("No scheduled reminders."), nil
	}
	list := sched.List(0)
	if len(list) == 0 {
		return mcp.NewToolResultText("No scheduled reminders."), nil
	}
	b, _ := json.MarshalIndent(list, "", "  ")
	return mcp.NewToolResultText(string(b)), nil
}

func (s *Server) handleCancel(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	chatID, err := req.RequireInt("chat_id")
	if err != nil {
		return mcp.NewToolResultError("chat_id is required"), nil
	}
	userID := int64(req.GetInt("user_id", 0))
	if !s.gate.ToolAllowed(int64(chatID), userID, config.ServerReminders) {
		return mcp.NewToolResultError("You are not allowed to manage reminders in this chat."), nil
	}
	id, err := req.RequireString("id")
	if err != nil {
		return mcp.NewToolResultError("id is required"), nil
	}
	sched, ok := s.sch.Scheduler(int64(chatID))
	if !ok {
		return mcp.NewToolResultError("this chat is not active"), nil
	}
	ok, err = sched.Remove(id)
	if err != nil {
		return mcp.NewToolResultError("failed to cancel: " + err.Error()), nil
	}
	if !ok {
		return mcp.NewToolResultText("No reminder with id " + id), nil
	}
	return mcp.NewToolResultText("Cancelled " + id), nil
}

func (s *Server) handleRecall(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	chatID, err := req.RequireInt("chat_id")
	if err != nil {
		return mcp.NewToolResultError("chat_id is required"), nil
	}
	userID := int64(req.GetInt("user_id", 0))
	if !s.gate.ToolAllowed(int64(chatID), userID, config.ServerMemory) {
		return mcp.NewToolResultError("Memory recall is not enabled in this chat."), nil
	}
	query, date := req.GetString("query", ""), req.GetString("date", "")
	if query == "" && date == "" {
		return mcp.NewToolResultError("provide a query or a date (DD-MM-YY)"), nil
	}
	out, err := s.recall.Recall(int64(chatID), query, date, int(req.GetFloat("limit", 0)))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(out), nil
}

func (s *Server) handlePropose(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	chatID, err := req.RequireInt("chat_id")
	if err != nil {
		return mcp.NewToolResultError("chat_id is required"), nil
	}
	userID := int64(req.GetInt("user_id", 0))
	if !s.gate.ToolAllowed(int64(chatID), userID, config.ServerMemory) {
		return mcp.NewToolResultError("Saving memory is not enabled in this chat."), nil
	}
	content, err := req.RequireString("content")
	if err != nil {
		return mcp.NewToolResultError("content is required"), nil
	}
	scope := req.GetString("scope", "long_term")
	msg, err := s.sink.Propose(ctx, int64(chatID), userID, scope, content)
	if err != nil {
		return mcp.NewToolResultError("could not propose memory: " + err.Error()), nil
	}
	return mcp.NewToolResultText(msg), nil
}

func describe(sc schedule.Schedule) string {
	if sc.Kind == schedule.KindCron {
		return "recurring job [" + sc.Spec + "]"
	}
	return "one-off reminder at " + sc.FireAt.Format(time.RFC3339)
}
